
URL=https://www.amazon.com/
location= //div[@id="glow-ingress-block"]
postal_code= //input[@autocomplete="postal-code"]
zipnumber=38852
apply=//span[@class="a-button a-button-span12"]
done= //button[@name="glowDoneButton"]
search_icon=//input[@id="nav-search-submit-button"]
add_cart_button=//input[@name="submit.add-to-cart"]
added_item=//h1[contains(text(), 'Added to cart')]

									