Env=Dev
Mode=Mobile
DeviceName = iPhone 12 Pro
URL=https://webtest.spinnyworks.in/


										III---HomePageElements----III
homepage_seeallcars = //div[@data-id='card-0']
homepage_SpinnyLogo = //a[@data-id='spinny-logo']
homepage_detectMyLocation = //button[@data-label='detect_homepage']
homepage_detectMyCurrentLocation = //button[@data-label='detect-current-location']
homepage_allowPermission = //android.widget.Button[@text='Allow']
homepage_delhiNCRCitySelectorSpinny = //div[@data-id='header_city_selector']
homepage_buyButton = //a[@data-id='header_buy']
homepage_sellButton = //a[@data-id='header_sell']
homepage_popularbrandscontainer = //div[@data-id='popular_brands']
homepage_marutisuzukibrand = //a[@data-id='popular_brand_maruti-suzuki']
homepage_explorePopularBrandsViewAllBrands = //button[@data-id='popular_brands_view_all']
homepage_explorePopularBrandsViewAllCars = //a[@data-id='popular_view_all_cars']
homepage_GetInstantOnlineQuote = //button[@class='styles__btn SellBannerTruebil__cta styles__primary styles__fullWidth'] 
homepage_latestAdditionSection = //div[@data-label='popular_cars'])[1]
homepage_popularCarsSection = //div[@data-label='popular_cars'])[2]
homepage_HowSpinnyWorksContainer = //div[@data-id='how-it-works-container']
homepage_watchHowItWorks = //button[@data-id='how-it-works-button']
homepage_videoOverlayContainer = //div[@data-id='video-player']
homepage_videoOverlayCloseButton = //i[@data-id='video-close']
homepage_watchHowItWorksLearnMore = //div[@class='HowItsWorkV3__learnMoreText']
homepage_watchHowItWorksBottomSheetOverlay = //div[@data-id='how-it-works-sheet']
homepage_HowSpinnyWorksLearnMoreWatchTheFilmButton = //button[@class='styles__btn styles__whitePurple LandingSection__bannerActionBtn']
homepage_watchHowItWorksCloseButton = //i[@data-id='video-close']
homepage_buyToggle = //div[@data-id='home_buy']
homepage_buyContentSection = //div[@data-id='home-buy-content']
homepage_buySectionContainer = //div[@data-id='home-buy-section']
homepage_buySectionLearnMore = //div[@data-id='buy_learn_more']
homepage_buyLearnMoreSpinnyAssuredContainer = //div[@data-id='spinny-assured']
homepage_buySectionLearnMoreAssuredLandingBackgroundImage = //div[@data-id='spinny-assured-image']
homepage_buySectionLearnMoreClose = //div[@data-id='assured-close']
homepage_browseCars = //a[@data-id='home_browse_cars']
homepage_sellToggle = //div[@data-id='home_sell']
homepage_sellSectionContentSection = //div[@data-id='buy-sell-tab']
homepage_sellToggleImageSection = //div[@data-id='home-sell-section']
homepage_sellToggleBenefitsSection = //div[@data-id='home-sell-section']
homepage_sellToggleBrandsContainer = //div[@data-id='home-sell-section']
homepage_getPrice = //a[@data-id='get-price-cta']
homepage_sellToggleGetPriceSellFormOverlay = //div[@data-id='sell-form-card']
homepage_hublocationSection = //div[@data-id='explore_hubs']
homepage_hublocationSectionHubCardDistance = //div[@data-id='hub-distance']
homepage_hublocationViewCars = //a[@data-id='hub_view_cars'] //button[@data-category='cta-btn']
homepage_hublocationViewAllCarsinGurgaon = //button[@data-id='hub_view_all']
homepage_downloadSpinnyAppBanner = //div[@data-id='download_app']
homepage_downloadSpinnyAppBannerDownloadAppButton = //div[@class='DownloadAppBanner__downloadAppCta DownloadAppBanner__margin'] //button[@data-id='download_app_button']
homepage_googlePlayButton = //div[@class='DownloadAppBanner__downloadAppCta DownloadAppBanner__margin'] //button[@data-id='download_app_button']
homepage_insightsThatDriveUsSection = //div[@data-id='insights']							
homepage_featuredSpinnyCarsContainer = //div[@data-id='featured_container']									
homepage_featuredBestBuyCarCard = //div[@data-id='Card-0']
homepage_featuredSpinnyCarsViewAllSpinnyCars = //a[@data-id='featured_view_all']
homepage_featuredNewlyAddedTab = //button[@data-id='featured_newly_added']
homepage_featuredSpinnyCarsNewAddedContainer = //div[@data-id='featured_container']
homepage_featuredNewlyAddedCarCard = //div[@data-id='Card-0']
homepage_featuredSpinnyCarsViewAllSpinnyCars = //a[@data-id='featured_view_all']
Carfinder_banner = //div[@data-id='car-finder']
Carfinder_pricerange = //div[@class='CarFinderQuestionnaire__nameDescriptionWrap']//p[contains(text(), 'Below 4 Lakh')]
Carfinder_lifestyle = //div[@data-label='lifestyle_category']//li[1]//div[1]
Carfinder_fueltype = //div[@data-label='fuel_type']//li[1]//div[1]
Carfinder_transmissiontype = //div[@data-label='transmission']//li[1]//div[1]
question_screen = //div[@class='CarFinderHeading__container']
spend = //h3[@class='CarFinderQuestionnaire__heading CarFinderQuestionnaire__addMargin']
category = //div[@class='CarFinderQuestionnaire__container styles__forGASectionSeen']//h3[@class='CarFinderQuestionnaire__heading']
optional = //div[@class='CarFinderQuestionnaire__container styles__forGASectionSeen']//div[3]//div[@class='CarFinderQuestionnaire__headingWrap CarFinderQuestionnaire__withHelpText']
carfinder_plp = //h1[@data-id='car-heading']
homepage_bodyTypeTabs = //div[@data-id='popular-by-body-tabs']
homepage_bodyTypeCardList = //div[@data-id='popular-by-body']
homepage_explorebodytypeViewAllHatchbacks = //a[@data-id='view-all-hatchback']
homepage_explorebodytypeSedan = //li[@data-id='body-sedan']
homepage_explorebodytypeSUV = //li[@data-id='body-suv']
homepage_explorebodytypeViewAllSUVs = //a[@data-id='view-all-suv']
homepage_explorebodytypeMUV = //li[@data-id='body-muv']
homepage_explorebodytypeViewAllMUVs = //a[@data-id='view-all-muv']
homepage_explorebodytypeLuxurySedan = //li[@data-id='body-luxury sedan']
homepage_explorebodytypeViewAllLuxurysedans = //a[@data-id='view-all-luxury sedan']
homepage_explorebodytypeViewAllSedans = //a[@data-id='view-all-sedan']

homepage_citySelector = //div[@data-id='header_city_selector']
homepage_DelhiNCR = //div[@data-id='Delhi NCR']
homepage_Bangalore = //div[@data-id='Bangalore']
homepage_Hyderabad = //div[@data-id='Hyderabad']
homepage_Mumbai = //div[@data-id='Mumbai']
homepage_Pune = //div[@data-id='Pune']
homepage_Delhi = //div[@data-id='Delhi']
homepage_Gurgaon = //div[@data-id='Gurgaon']
homepage_Noida = //div[@data-id='Noida']
homepage_Ahmedabad = //div[@data-id='Ahmedabad']
homepage_Chennai = //div[@data-id='Chennai']
homepage_Kolkata = //div[@data-id='Kolkata']
homepage_Lucknow = //div[@data-id='Lucknow']
homepage_Jaipur = //div[@data-id='Jaipur']
homepage_Chandigarh = //div[@data-id='Chandigarh']
homepage_Coimbatore = //div[@data-id='Coimbatore']
homepage_Ghaziabad = //div[@data-id='Ghaziabad']
homepage_Indore = //div[@data-id='Indore']
homepage_Kochi = //div[@data-id='Kochi']
homepage_Surat = //div[@data-id='Surat']
homepage_spinnyBuzzSection = //div[@data-id='good_press']
homepage_spinnyMaxHeadingBanner = //div[@data-id='spinny-max-heading']
homepage_spinnyMaxBannerContainer = //div[@data-id='spinny-max']
homepage_spinnyMaxBannerFirstCarCard = //div[@data-id='max-home-listing'] //div[@data-id='card-0']
homepage_spinnyMaxBannerExploreButton = //button[@data-id='max_explore']
homepage_spinnyMaxBannerViewMoreLuxuryCars = //a[@data-id='max_luxury_button']
homepage_spinnyMaxBannerShortlistIcon = //div[@data-category='luxury']
homepage_exploreMoreSectionContainer = //div[@data-id='explore_more']
homepage_checkEligiblity = //a[@data-id='explore_more_check_eligibility']
homepage_getExchangePrice = //a[@data-id='explore_more_get_exchange_price']
homepage_sellToggleGetPriceSellFormOverlay = //div[@data-id='sell-form-card']
homepage_exploreBuyBack = //button[@data-id='explore_more_explore_buyback']
homepage_buyBackBannerImage = //div[@data-id='buyback-landing']


										---MiscellaneousElements----
login_mobileNumber = //input[@name='login-mobile-number']
login_proceed = //div[@data-id='login-get-otp-button']
login_otp = //input[@id='login-otp']
account_logout = //div[@data-id='logout-button']
account_loginModalContainer = //form[@class='LoginModal__loginContainer']
MobileNumber=9999999991
otp=9876
botnav_account = //div[@data-id='nav-account']
botnav_bottomNavBar = //div[@class='styles__bottomNavItemListV2']
botnav_shortlist = //div[@data-id='nav-shortlists']
botnav_sellCar = //a[@data-id='nav-sellCar']
botnav_home = //a[@data-id='nav-home']
botnav_buyCar = //a[@data-id='nav-myCars'] //div[@data-id='']
shortlists_loginModalText = //h3[@class='LoginModal__loginHeading']
shortlists_backIcon =//i[@class='BackHeading__backIcon']
account_loginModalContainer = //form[@class='LoginModal__loginContainer']
applyFinance_spinnyCapitalContainer= //div[@class='UsedCarLoan__container']
applyFinance_usedCarLoanLandingSection = //div[@class='UsedCarLoan__landingSection']
homepage_buyBackContainer = //div[@class='BuyBackProgram__container BuyBackProgram__containerDesktop']


										III---SellPageElements----III
sellpage_spinnySellBanner = //div[@class='LandingForm__heading']
sellpage_sellPageContainer = //div[@class='styles__sellPageConatiner']
sellpage_sellFormCardHeading = //div[@class='SellFormOverlayV2__cardHeading']
sellpage_buyACar = //a[@href='/used-cars-in-delhi-ncr/s/']
sellpage_sellFormCardHeading = //div[@class='SellFormOverlayV2__cardHeading']



										III---ProductListingPageElements----III
plp_quickfiltermarutisuzuki = //div[@data-label='Maruti Suzuki']
plp_headingcontent = //h1[@class='HeadingContent__heading HeadingContent__addPadding']
plp_listingMainBanner = //div[@class='ListingMainBanner__container generics__d-f generics__ai-c']
plp_hubFilterApplied = //div[@class='styles__tab FilterTabs__filterChip']
plp_quickfilters = //ul[@class='FilterSortBar__filterSortBarContainer']
plp_hatchback_filter_applied = //div[@data-label='Hatchback']
plp_sedan_filter_applied = //div[@data-label='Sedan']
plp_explorebodytypeViewAllSedan = //a[@data-label='view_all_sedan']
plp_SUV_filter_applied = //div[@data-label='SUV']
plp_MUV_filter_applied = //div[@data-label='Muv']
plp_citySelectorDelhiNCR = //div[contains(@class, 'styles__headerLocation') and text()='Delhi NCR']
plp_usedCarInDelhiNCR = //h1[@class='HeadingContent__heading HeadingContent__addPadding' and text()= 'Used cars in Delhi NCR']
plp_citySelectorBangalore = //div[contains(@class, 'styles__headerLocation') and text()='Bangalore']
plp_usedCarInBangalore = //h1[@class='HeadingContent__heading HeadingContent__addPadding' and text()= 'Used cars in Bangalore']
plp_citySelectorHyderabad = //div[contains(@class, 'styles__headerLocation') and text()='Hyderabad']
plp_usedCarInHyderabad = //h1[@class='HeadingContent__heading HeadingContent__addPadding' and text()= 'Used cars in Hyderabad']
plp_citySelectorMumbai = //div[contains(@class, 'styles__headerLocation') and text()='Mumbai']
plp_usedCarInMumbai = //h1[@class='HeadingContent__heading HeadingContent__addPadding' and text()= 'Used cars in Mumbai']
plp_citySelectorPune = //div[contains(@class, 'styles__headerLocation') and text()='Pune']
plp_usedCarInPune = //h1[@class='HeadingContent__heading HeadingContent__addPadding' and text()= 'Used cars in Pune']
plp_citySelectorDelhi = //div[contains(@class, 'styles__headerLocation') and text()='Delhi']
plp_usedCarInDelhi = //h1[@class='HeadingContent__heading HeadingContent__addPadding' and text()= 'Used cars in Delhi']
plp_citySelectorGurgaon = //div[contains(@class, 'styles__headerLocation') and text()='Gurgaon']
plp_usedCarInGurgaon = //h1[@class='HeadingContent__heading HeadingContent__addPadding' and text()= 'Used cars in Gurgaon']
plp_citySelectorNoida = //div[contains(@class, 'styles__headerLocation') and text()='Noida']
plp_usedCarInNoida = //h1[@class='HeadingContent__heading HeadingContent__addPadding' and text()= 'Used cars in Noida']
plp_citySelectorAhmedabad = //div[contains(@class, 'styles__headerLocation') and text()='Ahmedabad']
plp_usedCarInAhmedabad = //h1[@class='HeadingContent__heading HeadingContent__addPadding' and text()= 'Used cars in Ahmedabad']
plp_citySelectorChennai = //div[contains(@class, 'styles__headerLocation') and text()='Chennai']
plp_usedCarInChennai = //h1[@class='HeadingContent__heading HeadingContent__addPadding' and text()= 'Used cars in Chennai']
plp_citySelectorKolkata = //div[contains(@class, 'styles__headerLocation') and text()='Kolkata']
plp_usedCarInKolkata = //h1[@class='HeadingContent__heading HeadingContent__addPadding' and text()= 'Used cars in Kolkata']
plp_citySelectorLucknow = //div[contains(@class, 'styles__headerLocation') and text()='Lucknow']
plp_usedCarInLucknow = //h1[@class='HeadingContent__heading HeadingContent__addPadding' and text()= 'Used cars in Lucknow']
plp_citySelectorJaipur = //div[contains(@class, 'styles__headerLocation') and text()='Jaipur']
plp_usedCarInJaipur= //h1[@class='HeadingContent__heading HeadingContent__addPadding' and text()= 'Used cars in Jaipur']
plp_citySelectorChandigarh = //div[contains(@class, 'styles__headerLocation') and text()='Chandigarh']
plp_usedCarInChandigarh = //h1[@class='HeadingContent__heading HeadingContent__addPadding' and text()= 'Used cars in Chandigarh']
plp_citySelectorCoimbatore = //div[contains(@class, 'styles__headerLocation') and text()='Coimbatore']
plp_usedCarInCoimbatore = //h1[@class='HeadingContent__heading HeadingContent__addPadding' and text()= 'Used cars in Coimbatore']
plp_citySelectorGhaziabad = //div[contains(@class, 'styles__headerLocation') and text()='Ghaziabad']
plp_usedCarInGhaziabad = //h1[@class='HeadingContent__heading HeadingContent__addPadding' and text()= 'Used cars in Ghaziabad']
plp_citySelectorIndore = //div[contains(@class, 'styles__headerLocation') and text()='Indore']
plp_usedCarInIndore = //h1[@class='HeadingContent__heading HeadingContent__addPadding' and text()= 'Used cars in Indore']
plp_citySelectorKochi = //div[contains(@class, 'styles__headerLocation') and text()='Kochi']
plp_usedCarInKochi = //h1[@class='HeadingContent__heading HeadingContent__addPadding' and text()= 'Used cars in Kochi']
plp_citySelectorSurat = //div[contains(@class, 'styles__headerLocation') and text()='Surat']
plp_usedCarInSurat = //h1[@class='HeadingContent__heading HeadingContent__addPadding' and text()= 'Used car in Surat']
plp_SpinnyMaxCars_filter_applied = //div[@data-label='Spinny Max Cars']
plp_cityselectorallcitiescontainer = //div[@class='styles__citiesContainer']
plp_cityselectorAhmedabad = //div[@data-label='Ahmedabad']
plp_citySelectorContainer= //div[@data-label='city-selector-menu']
plp_CitySelector = //div[@class='HeaderV2__citySelctorWrap']
plp_citySelectBangalore = //div[@data-label='Bangalore']
plp_floatingCallButton = //div[@class='BottomNavFilters__callChatWrap']
plp_floatingSortFilter = //li[@data-category='filter-sort-bar'][1]
plp_floatingSortFilterPriceLowToHigh = //div[@class='SortOverlay__listItem'][1]
plp_floatingSortFilterPriceLowToHighAppliedPLP = //li[@data-category='filter-sort-bar' and text()= 'Price - Low to High']
plp_floatingSortFilterPriceHighToLow = //div[@class='SortOverlay__listItem'][2]
plp_floatingSortFilterPriceHighToLowAppliedPLP = //li[@data-category='filter-sort-bar' and text()= 'Price - High to Low']
plp_floatingSortFilterKMDrivenLowToHigh = //div[@class='SortOverlay__listItem'][3]
plp_floatingSortFilterKMDrivenLowToHighAppliedPLP = //li[@data-category='filter-sort-bar' and text()= 'KM Driven - Low to High']
plp_floatingSortFilterYearNewToOld = //div[@class='SortOverlay__listItem'][4]
plp_floatingSortFilterYearNewToOldAppliedPLP = //li[@data-category='filter-sort-bar' and text()= 'Year - New to Old']
plp_floatingSortFilterNewestFirst = //div[@class='SortOverlay__listItem'][5]
plp_floatingSortFilterNewestFirstAppliedPLP = //li[@data-category='filter-sort-bar' and text()= 'Newest First']


										III---ProductDetailPageElements----III
pdp_whatsappIcon = //div[@data-label='whatsapp']
pdp_threeSixtyViewCard = //div[@data-label='three-sixty-view']



