Env=Dev
Mode=Mobile
DeviceName = iPhone X
URL=https://www.spinny.com/	

										---HomePageElements----
homepage_seeallcars = //div[@class='TopBannerTruebil__content']//a[@data-label='See All Cars btn click btn click']
homepage_SpinnyLogo = //a[@data-label='header-spinny-logo']
homepage_detectMyLocation = //button[@data-label='detect_homepage']
homepage_detectMyCurrentLocation = //button[@data-label='detect-current-location']
homepage_allowPermission = //android.widget.Button[@text='Allow']
homepage_delhiNCRCitySelectorSpinny = //div[@class='HeaderV2__citySelctorWrap']
homepage_buyButton = //a[@data-label='buy-car']
homepage_sellButton = //a[@data-label='sell-car']
homepage_popularbrandscontainer = //div[@class='PopularBrands__container styles__forGASectionSeen PopularBrands__mobileView']
homepage_marutisuzukibrand = //a[@data-label='maruti-suzuki']
homepage_SpinnyLogo = //a[@data-label='header-spinny-logo']
homepage_explorePopularBrandsViewAllBrands = //button[@class='PopularBrands__viewAll']
homepage_explorePopularBrandsViewAllCars = //a[@data-category='popular_brands_view_all_btn']
homepage_GetInstantOnlineQuote = //button[@class='styles__btn SellBannerTruebil__cta styles__primary styles__fullWidth']
homepage_latestAdditionSection = //div[@data-label='popular_cars'])[1]
homepage_popularCarsSection = //div[@data-label='popular_cars'])[2]
homepage_searchCarsByBudget = //div[@class='SeeCarsBudget__container']
homepage_2to4LakhRange = //a[@href='/used-cars-over-2-lakh-rs-under-4-lakh-rs/s/']
homepage_HowSpinnyWorksContainer = //div[@class='HowItsWorkV2__container HowItsWorkV2__noCTA']
homepage_watchHowItWorks = //button[@data-category='how_it_works']
homepage_videoOverlayContainer = //div[@class='VideoPlayer__videoContainer']
homepage_videoOverlayCloseButton = //i[@class='VideoOverlay__modalCloseBtn']
homepage_watchHowItWorksLearnMore = //div[@class='HowItsWorkV2__learnMore']
homepage_watchHowItWorksBottomSheetOverlay = //div[@class='styles__bottomSheetOverlay HowItsWorkV2__addZIndex']
homepage_HowSpinnyWorksLearnMoreWatchTheFilmButton = //button[@class='styles__btn styles__whitePurple LandingSection__bannerActionBtn']
homepage_watchHowItWorksCloseButton = //i[@class='BackHeading__closeIcon']
homepage_buyToggle = //div[@class='BuyAndSellTabV2__tabItem BuyAndSellTabV2__active']
homepage_buyContentSection = //div[@class='BuySection__contentSection']
homepage_buySectionContainer = //div[@class='BuySection__container']
homepage_buySectionLearnMore = //div[@class='BuySection__learnMore']
homepage_buyLearnMoreSpinnyAssuredContainer = //div[@class='SpinnyAssured__spinnyAssuredContainer']
homepage_buySectionLearnMoreAssuredLandingBackgroundImage = //div[@class='styles__backgroundImageWrapper styles__withShadow AssuredLandingSection__bannerWrap AssuredLandingSection__assuredPageInBudgetCityWrap']
homepage_buySectionLearnMoreClose = //div[@class='SpinnyAssured__circle']
homepage_browseCars = //a[@data-category='home']
homepage_sellToggle = //div[@class='BuyAndSellTabV2__tabItem']
homepage_sellSectionContentSection = //div[@class='BuyAndSellTabV2__contentSection']
homepage_sellToggleImageSection = //div[@class='SellSection__imgSection']
homepage_sellToggleBenefitsSection = //div[@class='SellSection__benefits']
homepage_sellToggleBrandsContainer = //div[@class='SellSection__brandsContainer']
homepage_getPrice = //a[@href='/check-car-valuation/']
homepage_sellToggleGetPriceSellFormOverlay = //div[@class='SellFormOverlayV2__cardContainer SellFormOverlayV2__pseudoCardVisible']
homepage_hublocationSection = //div[@class='ExploreHubs__hubsDetailWrapper ExploreHubs__addSpacing styles__forGASectionSeen']
homepage_hublocationSectionHubCardDistance = //div[@class='HubCard__distance']
homepage_hublocationViewCars = //button[@data-label='hub cta']
homepage_hublocationViewAllCarsinGurgaon = //button[@class='styles__btn ExploreHubs__bottomLinkText styles__purpleOutline styles__fullWidth']
homepage_downloadSpinnyAppBanner = //div[@class='DownloadAppBanner__downloadAppBannerMain']
homepage_downloadSpinnyAppBannerDownloadAppButton = //button[@class='DownloadAppButton__downloadAppButtonContainer DownloadAppButton__fullScreen DownloadAppButton__light DownloadAppButton__center']
homepage_googlePlayButton = //button[@class='DownloadAppButton__downloadAppButtonContainer DownloadAppButton__fullScreen DownloadAppButton__light DownloadAppButton__center']
										---MiscellaneousElements----
login_mobileNumber = //input[@name='login-mobile-number']
login_proceed = //button[@data-label='proceed button']
login_otp = //input[@name='login-otp']
account_logout = //button[@data-label='header-logout-btn']
account_loginModalContainer = //form[@class='LoginModal__loginContainer']
MobileNumber=9999999991
otp=9876
botnav_account = //div[@data-label='Account']
botnav_bottomNavBar = //div[@class='styles__bottomNavItemListV2']
botnav_shortlist = //div[@class='styles__shorlistIconWrap']
botnav_sellCar = //a[@href='/sell-used-car/']
botnav_home = //a[@data-abel='Home']
botnav_buyCar = //a[@data-abel='Buy Car']
shortlists_loginModalText = //h3[@class='LoginModal__loginHeading']
shortlists_backIcon =//i[@class='BackHeading__backIcon']
account_loginModalContainer = //form[@class='LoginModal__loginContainer']

										---SellPageElements----
sellpage_spinnySellBanner = //div[@class='LandingForm__heading']
sellpage_sellPageContainer = //div[@class='styles__sellPageConatiner']
sellpage_sellFormCardHeading = //div[@class='SellFormOverlayV2__cardHeading']
sellpage_buyACar = //a[@data-label='buy-car']


										---ProductListingPageElements----
plp_quickfiltermarutisuzuki = //div[@data-label='Maruti Suzuki']
plp_headingcontent = //h1[@class='HeadingContent__heading HeadingContent__addPadding']
plp_listingMainBanner = //div[@class='ListingMainBanner__container generics__d-f generics__ai-c']
plp_hubFilterApplied = //div[@class='styles__tab FilterTabs__filterChip']
plp_quickfilters = //ul[@class='FilterSortBar__filterSortBarContainer']
